### ISSUE TITLE
no output

### ISSUE THREAD

**Issue by aboudiua** [makevoid/opensea-images-downloader#3]
hi, i downloaded the ruby and bundler and ran the commands ,everything seems fine but when i run the last command for scraping it displays no error and end the command directly , the scraping isnt finished and there are no photos in the output file

**Comment by aboudiua** [comment]
update : it worked on other collections but couldnt work on the one i want (bored cat club) https://opensea.io/collection/boredcatclub
i dont know why ,it starts at offset=0 and doesnt continue

**Comment by aboudiua** [comment]
update :png file doesnt open

**Comment by makevoid** [comment]
I think it's a problem of opensea API, this collection doesn't work on their API

you can see that this API URL contains no data:

https://api.opensea.io/api/v1/assets?order_direction=desc&limit=50&collection=boredcatclub&offset=0

if you want you can try contacting OpenSea support to ask them if they can fix it https://support.opensea.io/hc/en-us/requests/new 
and then you can try again

( btw this URL works btw but it's not the API url we need to get the images https://api.opensea.io/api/v1/collection/boredcatclub so the bug seems limited only to the one above )

as this is a bug of opensea and not of the images-downloader project I'm closing the issue
